project:
  mq:
    host: rchmfgd.pok.dst.ibm.com
    port: 1420
    queue-manager: DMQ001
    channel: DMQ001.SERVER  # SVRCONN
    #username: mqm
    #password: 123456
    receive-timeout: 2000
    queue: SOVA.INPUT